import {
  Accessibility,
  Activity,
  AlarmClock,
  Ambulance,
  Anvil,
  Apple,
  Armchair,
  Atom,
  Award,
  Baby,
  Backpack,
  Ban,
  Banana,
  Bandage,
  Bath,
  BatteryCharging,
  Bean,
  Bed,
  BeerOff,
  Bell,
  Bike,
  Binoculars,
  Bird,
  Bone,
  Book,
  Bookmark,
  BookMarked,
  BookOpen,
  Brain,
  BrainCircuit,
  BrainCog,
  Briefcase,
  Broom,
  Brush,
  Bug,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  Carrot,
  Cat,
  ChartColumn,
  ChefHat,
  Cherry,
  CigaretteOff,
  CircleCheck,
  Citrus,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  CloudSun,
  Clover,
  Code,
  Coffee,
  Compass,
  Cookie,
  CookingPot,
  Crosshair,
  CupSoda,
  Dice5,
  Dna,
  Dog,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Egg,
  Eye,
  Feather,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  Globe,
  GraduationCap,
  Grape,
  Guitar,
  Hammer,
  Hand,
  HandHeart,
  Hash,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Highlighter,
  Hourglass,
  House,
  IceCreamCone,
  Infinity as InfinityIcon,
  Key,
  Lamp,
  Languages,
  Laptop,
  Leaf,
  LeafyGreen,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  Medal,
  MessageCircle,
  Mic,
  Milk,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  Move,
  Music,
  NotebookPen,
  Palette,
  Paintbrush,
  PartyPopper,
  PawPrint,
  PenLine,
  Percent,
  PersonStanding,
  Piano,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plus,
  Puzzle,
  Recycle,
  Salad,
  Sandwich,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  SprayCan,
  Sprout,
  Star,
  Stethoscope,
  StretchHorizontal,
  Sun,
  Sunrise,
  Swords,
  Syringe,
  Target,
  Tent,
  Thermometer,
  Timer,
  Trash,
  TreePine,
  Trees,
  TrendingUp,
  Trophy,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Weight,
  Wind,
  WineOff,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';
import { Text, type StyleProp, type TextStyle } from 'react-native';

import { DEFAULT_HABIT_ICON } from '@/utils/habit-icons';

const HABIT_ICON_COMPONENTS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  activity: Activity,
  'alarm-clock': AlarmClock,
  ambulance: Ambulance,
  anvil: Anvil,
  apple: Apple,
  armchair: Armchair,
  atom: Atom,
  award: Award,
  baby: Baby,
  backpack: Backpack,
  ban: Ban,
  banana: Banana,
  bandage: Bandage,
  bath: Bath,
  'battery-charging': BatteryCharging,
  bean: Bean,
  bed: Bed,
  'beer-off': BeerOff,
  bell: Bell,
  bike: Bike,
  binoculars: Binoculars,
  bird: Bird,
  bone: Bone,
  book: Book,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  bookmark: Bookmark,
  brain: Brain,
  'brain-circuit': BrainCircuit,
  'brain-cog': BrainCog,
  briefcase: Briefcase,
  broom: Broom,
  brush: Brush,
  bug: Bug,
  bus: Bus,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  carrot: Carrot,
  cat: Cat,
  'chart-column': ChartColumn,
  'chef-hat': ChefHat,
  cherry: Cherry,
  'cigarette-off': CigaretteOff,
  'circle-check': CircleCheck,
  citrus: Citrus,
  clapperboard: Clapperboard,
  'clipboard-list': ClipboardList,
  clock: Clock,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  'cloud-sun': CloudSun,
  clover: Clover,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  cookie: Cookie,
  'cooking-pot': CookingPot,
  crosshair: Crosshair,
  'cup-soda': CupSoda,
  'dice-5': Dice5,
  dna: Dna,
  dog: Dog,
  droplet: Droplet,
  droplets: Droplets,
  dumbbell: Dumbbell,
  ear: Ear,
  egg: Egg,
  eye: Eye,
  feather: Feather,
  film: Film,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  'flower-2': Flower2,
  footprints: Footprints,
  'gamepad-2': Gamepad2,
  gift: Gift,
  'glass-water': GlassWater,
  globe: Globe,
  'graduation-cap': GraduationCap,
  grape: Grape,
  guitar: Guitar,
  hammer: Hammer,
  hand: Hand,
  'hand-heart': HandHeart,
  hash: Hash,
  headphones: Headphones,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  'heart-pulse': HeartPulse,
  highlighter: Highlighter,
  hourglass: Hourglass,
  house: House,
  'ice-cream-cone': IceCreamCone,
  infinity: InfinityIcon,
  key: Key,
  lamp: Lamp,
  languages: Languages,
  laptop: Laptop,
  leaf: Leaf,
  'leafy-green': LeafyGreen,
  lightbulb: Lightbulb,
  'list-checks': ListChecks,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  medal: Medal,
  'message-circle': MessageCircle,
  mic: Mic,
  milk: Milk,
  monitor: Monitor,
  moon: Moon,
  'moon-star': MoonStar,
  mountain: Mountain,
  move: Move,
  music: Music,
  'notebook-pen': NotebookPen,
  palette: Palette,
  paintbrush: Paintbrush,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  'pen-line': PenLine,
  percent: Percent,
  'person-standing': PersonStanding,
  piano: Piano,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  plus: Plus,
  puzzle: Puzzle,
  recycle: Recycle,
  salad: Salad,
  sandwich: Sandwich,
  scissors: Scissors,
  shield: Shield,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'shower-head': ShowerHead,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sofa: Sofa,
  soup: Soup,
  sparkles: Sparkles,
  'spray-can': SprayCan,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  'stretch-horizontal': StretchHorizontal,
  sun: Sun,
  sunrise: Sunrise,
  swords: Swords,
  syringe: Syringe,
  target: Target,
  tent: Tent,
  thermometer: Thermometer,
  timer: Timer,
  trash: Trash,
  'tree-pine': TreePine,
  trees: Trees,
  'trending-up': TrendingUp,
  trophy: Trophy,
  umbrella: Umbrella,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  weight: Weight,
  wind: Wind,
  'wine-off': WineOff,
  wrench: Wrench,
  zap: Zap,
};

export function getHabitLucideIcon(iconId: string): LucideIcon | null {
  return HABIT_ICON_COMPONENTS[iconId] ?? null;
}

export function HabitIcon({
  icon,
  size = 20,
  color = '#555555',
  strokeWidth = 2,
  style,
}: {
  icon: string | null | undefined;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: StyleProp<TextStyle>;
}) {
  const iconId = icon || DEFAULT_HABIT_ICON;
  const Lucide = HABIT_ICON_COMPONENTS[iconId];

  if (Lucide) {
    return <Lucide size={size} color={color} strokeWidth={strokeWidth} />;
  }

  // Legacy emoji (or unknown) — leave as-is
  return (
    <Text style={[{ fontSize: size * 0.95, lineHeight: size * 1.15 }, style]}>{iconId}</Text>
  );
}
